export const GENRES = {
  fantasy: 'Fantasy',
  scifi: 'Science Fiction',
  dystopian: 'Dystopian',
  adventure: 'Adventure',
  romance: 'Romance',
  detective: 'Detective',
  horror: 'Horror',
  thriller: 'Thriller',
  lgbtq: 'LGBTQ+',
  historicalfic: 'Historical Fiction',
  childrenfic: "Children's fiction",
  ya: 'Young adult',
  na: 'New adult',
  ero: 'Erotica',
  fanfic: 'Fanfiction',
  autobiomemoirs: 'Memoir & Autobiography',
  bio: 'Biography',
  historical: 'Historical',
  inspirational: 'Inspirational',
  social: 'Social Sciences',
  economy: 'Economy',
  politics: 'Politics',
  philosophy: 'Philosophy',
  business: 'Business',
  family: 'Families & Relationships',
  spirituality: 'Spirituality, Religion',
  personalgrowth: 'Personal growth',
  truecrime: 'True crime',
}
